name: "ZIP Repo"
description: "Create a ZIP file from the repository, excluding selected files"
inputs:
  output-path:
    description: "Absolute path with filename of the ZIP file to create"
    required: true
    default: ""
  exclude-patterns:
    description: "File patterns to exclude from package. Patterns must be white space separated"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    # Add action's path so that pack.py can be found
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: pack.py ${{ inputs.output-path }} "${{ inputs.exclude-patterns }}"
      shell: bash
