name: "EMS Package"
description: "Create a production documentation (zip) for EMS"
inputs:
  exclude-patterns:
    description: "File patterns to exclude from package"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - run: ls
      shell: bash
    # Add action's path so that pack.py can be found
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: pack.py "${{ inputs.exclude-patterns }}"
      shell: bash
